### ISSUE TITLE
Marquee Speed Suggestion/Feature

### ISSUE THREAD

**Issue by knowj** [aamirafridi/jQuery.Marquee#1]
Feature request:
Currently the speed is based on the milliseconds which is great if you are working with a static width (It takes 10,000ms to move 800px). However as the content area expands the speed of the marquee increases to potentially un-manageable/un-readable speed.

Suggestion:
Calculate the speed based on distance/time. It would probably be worth having an option to add a parent container that would be taken into account in the speed calculation.

`<div class="marquee-container">
### </ul>

</div>`

This approach would mean that the scroll speed would be consistent whether the scrolling content is 500px or 5000px.

**Comment by sachinverma1811** [comment]
Hi everyone,
I know this conversation are to old but i need your help.
I just used this plugin in my website. Everything is working perfectly.
I have a requirements to control the scrolling speed (increase or decrease) on users clicks on faster/slower buttons.

Can anyone help me to achieve this.???

**Comment by GiorgosK** [comment]
when using `duplicated: true` the speed is not same anymore 
duplicated the test case above and added extra option 
http://jsfiddle.net/GiorgosK/1ohk07vw/

**Comment by aamirafridi** [comment]
Try duration: http://jsfiddle.net/aamir/nmo8xkw4/

**Comment by GiorgosK** [comment]
@aamirafridi it seems the speed is not the same still
