### ISSUE TITLE
Calling marquee from javascript

### ISSUE THREAD

**Issue by PriNet** [aamirafridi/jQuery.Marquee#100]
I'm having a problem getting the marquee script to "start" scrolling when I change the DOM to change the contents of the scroll DIV, here's what I have tried, please let me know if there is another way to change the scroll text "on the fly" is this is all wrong:

``	umNew = document.createElement('DIV');
	umNew.id = 'Marquee';
	umNew.className = 'marquee';
	umNew_content = document.createTextNode('test string');
	umNew.appendChild(umNew_content);
	umOld = document.getElementById('Marquee');
	parentDiv = umOld.parentNode;
	parentDiv.replaceChild(umNew,umOld);
``

thanx for any ideas

**Comment by nuke-ellington** [comment]
Please take a look at the "destroy" method the plug-in provides:
https://github.com/aamirafridi/jQuery.Marquee#methods

**Comment by aamirafridi** [comment]
As @nuke-ellington mentioned, check the example https://github.com/aamirafridi/jQuery.Marquee#how-to-use-methods
