### ISSUE TITLE
Check for media="print" on style tag before inserting animation

### ISSUE THREAD

**Issue by superpowered** [aamirafridi/jQuery.Marquee#105]
Wordpress by default adds a style block to the end of the head for print styles. If there are no other style tags on the site, this script will sometimes choose the print style block and put the animation inside of it, causing it not to work.

<img width="756" alt="screen shot 2017-04-20 at 11 38 01 am" src="https://cloud.githubusercontent.com/assets/7035467/25242046/e2c20d36-25bd-11e7-8e31-14774b9e3a8b.png">

**Comment by aamirafridi** [comment]
Looking at the code https://github.com/aamirafridi/jQuery.Marquee/blob/master/jquery.marquee.js#L401-L410 I am not sure why will it append css to the style in head?

**Comment by naveed-fida** [comment]
The css is applied directly to the element in JS which means they are included inline. Your problem may be different. Closing this issue.
