### ISSUE TITLE
fixing position to the bottom

### ISSUE THREAD

**Issue by behzadbabaei** [aamirafridi/jQuery.Marquee#109]
Hi 
I developed the following code in order to show the marquees and switching between them but when I want to fix the parent div to the bottom (adding position:fixed or absolute) it disappears and does not function properly.have you ever faced the same Issue?
`<div style="direction: ltr !important;" id="footertemplate"  class="" data-srctools="">
            <div data-show="no" data-priority="1" id="i1" class='marquee'
                 data-duration='10000' data-direction="right" data-duplicated='false' >this is sample test</label>
            </div>
        </div>`

`
<script type="text/javascript">
    $( ".marquee" ).first().data('show','yes');
    function MarqueeDiv() {
        $(".marquee").each(function(){
            var id=$(this).attr('id');
            var num=$('.marquee').length;
            if($(this).data('show')=='yes'){
                $('#'+id).show();
                $('#'+id).bind('finished', function () {
                    $('#'+id).data('show','no');
                    var priority=parseInt($('#'+id).data('priority'));
                    if(priority==num){
                        $('#i1').data('show','yes');
                    }
                    else {
                        $('#i'+(priority+1)).data('show','yes');
                    }
                    if(num!='1'){
                        $('#'+id).data('show','no');
                    }
                    $('#'+id).marquee('destroy');
                    MarqueeDiv();
                }).marquee({
                    duration:$('#'+id).data('duration'),
                    startVisible: false,
                    direction: $('#'+id).data('direction'),
                    duplicated: $('#'+id).data('duplicated'),
                });
            }
            else{
                $('#'+id).hide();
                // console.log("the div with id:"+id+ " is hidden.");
            }

        });
    }
    MarqueeDiv();
</script>`

**Comment by nuke-ellington** [comment]
Not able to duplicate the behavior. Could you please provide a working example?

**Comment by naveed-fida** [comment]
Closing. Working example not provided. If someone has the same problem, please open a new issue.
