### ISSUE TITLE
Marquee Appear After White Space

### ISSUE THREAD

**Issue by cassimv** [aamirafridi/jQuery.Marquee#111]
I have a Jquery Marquee with three elements scrolling horizontally with duplicate set to true. 

The fiddle setup can be found here: 

https://jsfiddle.net/vmna6k7s/4/

The scroll works the first two times but on the third time elements appear after some white space. 

Any ideas as to how this could be fixed ?

**Comment by nuke-ellington** [comment]
Please have a look into the gap [option](https://github.com/aamirafridi/jQuery.Marquee#options).
