### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by QRMarketing** [aamirafridi/jQuery.Marquee#115]
Plugin does not work in Safari. It does not animate. I see the negative margin amounts counting, but Safari does not handle well negative left margins. Tried adding position:relative, helps but not with the plugins duplicate feature (display block or inline does not help). Also the mouse over does not work.

So this plugin is challenging for cross browser use, with this conflicting css issue in Safari. Works in other browsers.

Ref link: https://stackoverflow.com/questions/24829920/safari-not-recognizing-negative-margin-top
http://www.456bereastreet.com/lab/float_negative_margins/

**Comment by Robiv8** [comment]
Hallo, i have OSX El Capitan and Safari and its Working! In the Preview.
Maybe you have a other Problem?

**Comment by naveed-fida** [comment]
Works on the Safari browsers I've tested on. Would be great to know which version the OP is talking about. Closing for now.
