### ISSUE TITLE
Tearing Issue under macOS & Intel GraphicsCard & Chome

### ISSUE THREAD

**Issue by daslicht** [aamirafridi/jQuery.Marquee#123]
Hello,
I get the following redraw errors on Mac's which have a _Intel GraphicsCard_ in Google Chome:

![](https://i.imgur.com/18TE8SX.png)

Any idea how to fix this issue ?

~ Marc

**Comment by nuke-ellington** [comment]
I never experienced this issue with the same combination of hard- and software.
Could you please provide a working example to replicate this behavior?

**Comment by daslicht** [comment]
I solved it meanwhile.
This happens when the lineheight is smaller than 1

Thank you for teh Reply !
~ Marc
