### ISSUE TITLE
Marquee broken in RTL layout

### ISSUE THREAD

**Issue by longzheng** [aamirafridi/jQuery.Marquee#125]
When used on a page/element with ```dir="rtl"``` then the marquee is broken.

Demo: http://jsfiddle.net/keboatLL/2/

**Comment by mohamedaitbella** [comment]
yes the same problem here

**Comment by mohamedaitbella** [comment]
you can use this 
data-direction='right' dir="ltr"
demo 
http://jsbin.com/howike/1/edit?html,js,output

**Comment by AbdallahBedir** [comment]
Thanks @mohamedaitbella It works.
