### ISSUE TITLE
Marquee causes page to crash after prolonged period of time

### ISSUE THREAD

**Issue by no-mayo** [aamirafridi/jQuery.Marquee#131]
The marquee keeps crashing causing my [website](http://barbaracreative.com/) to crash after it's been idle for a while.
This happens when the website stays open in a tab for more than 5 minutes, while users browse other sites in a different tab. When you come back to the website, it's frozen and then crashes - I am confident that it is jquery marquee causing this - does anyone have any ideas why?

Below is relevant code snippet:
 
    // Load dependencies
    const Marquee3k = require("marquee3000");
    const throttle = require("lodash.throttle");

    document.addEventListener("DOMContentLoaded", function() {
      Marquee3k.init();
      carousel.init();
    // On window resize, re-initialise certain things

    window.addEventListener(
      "resize",
      throttle(function() {
        carousel.init();
        // Marquee3k.refreshAll(); // this does not appear to work

        window.setTimeout(function() {
          masonryGrid.refresh();
        }, 750);
      }, 1000)
    );

**Comment by nuke-ellington** [comment]
It appears that you are using another plugin. Please post your support request to the correct [issue tracker](https://github.com/ezekielaquino/Marquee3000/issues).

**Comment by nusson** [comment]
We have the same bug
we tried to implement marquee3k (not the jquery version thow) on 2 website on a 1year span, and only those 2 websites had this exact same bug

we don't figure when the freeze append, but it's always the same thing, the tab just freeze, and we are unable to close it
only by force killing chrome...

So we expect that it is this marquee3000 lib that bug ;)
