### ISSUE TITLE
No Animation on iOS 11.3 (what did I do wrong?)

### ISSUE THREAD

**Issue by rcooke** [aamirafridi/jQuery.Marquee#132]
I'm assuming the fault is mine, but would appreciate any guidance or suggestions.

I desire a multi-string marquee on my site.  I copied the code you posted to another user here:

[https://codepen.io/anon/pen/JpGYMV](https://codepen.io/anon/pen/JpGYMV)

I cloned your master branch and copied `jquery.marquee.min.js` to my server's static folder.

I'm testing on desktops, old iPad, and an iPhone6s+.

The marquee works as expected everyplace BUT the iPhone!

On the iPhone it shows all my headlines vertically, and scrolls them all RTL as a group. I'm using Bootstrap3 for "responsive" layout.  I'm new to Bootstrap so perhaps I have a bad setting there?

I'll be fiddling with stuff looking for anything affects this.  But there are so many variables at play I would greatly appreciate any input!

Thanks in advance.

**Comment by aamirafridi** [comment]
Which iPhone (5/6/7?) and which browser?
