### ISSUE TITLE
Black box over text during JQuery fade

### ISSUE THREAD

**Issue by Gaveroid** [aamirafridi/jQuery.Marquee#134]
When I try to fade the containing element out using JQuery, whether it be $('element').fadeOut(2000), a little semi-transparent black box appears over a portion of the div at the very right during the transition. This does not happen when the marquee is not active. Is there a known incompatibility with this and fading out/in? I'm viewing the page in Google Chrome. A JQuery animate of the opacity to 0% does nothing and doesn't change the appearance. I also noticed that when fading out and back in, the marquee restarts.

**Comment by naveed-fida** [comment]
Wasn't able to reproduce this.
