### ISSUE TITLE
Finished event takes a very long time to fire

### ISSUE THREAD

**Issue by Gaveroid** [aamirafridi/jQuery.Marquee#135]
I'm trying to reload the information in my marquee after it has finished scrolling. The finished event takes a very long time to fire - sometimes 10-20 seconds after all the text has scrolled by. If I increase the speed a lot, it takes less time to fire after finishing but still takes a very long time. I'm viewing the page in Google Chrome.

**Comment by aamirafridi** [comment]
Do you have demo link please? The demo looks fine to me here https://codepen.io/aamirafridi/pen/shqKg

**Comment by naveed-fida** [comment]
Finished works as intented, i.e it'll fire each time the marquee test slides off the screen.
