### ISSUE TITLE
Issue with the duplicated and infinite scroll

### ISSUE THREAD

**Issue by dholakiyaankit** [aamirafridi/jQuery.Marquee#139]
I have been trying to get rid of this problem but some how unable to, and I can not see any options for this issue. if you look at this [codepen ](https://codepen.io/dholakiyaankit/pen/eKmdjG).

The issue is width is big and content is less. So, after every one round the text is being added at the end which user can see. What I want to is infinite marquee without being added later.

Can you someone please let me know how to achieve this?

**Comment by aamirafridi** [comment]
If the content is too small, try duplicating it yourself a couple of times. e.g. https://codepen.io/anon/pen/vrLbMw

Ideally this plugin should check if the content is too small, than it should keep duplicate the content until it exceeds the container width. (easy to implement if you want to try and create a PR 😉)

At the moment there is no built in way
