### ISSUE TITLE
Jquery Marquee after loop trigger an event

### ISSUE THREAD

**Issue by Girish-Reddy** [aamirafridi/jQuery.Marquee#142]
marq = "<marquee class='marqueeOne' scrollamount='22' onfinish='WriteInfo(event)' loop='1'>"+ul+"</marquee>";           
  $(".marquee").html(marq);

onfinish event is not triggering after one loop

**Comment by aamirafridi** [comment]
Can you check the demos. You can find an example there. Sorry cannot understand your code.
