### ISSUE TITLE
Non-Smooth Option

### ISSUE THREAD

**Issue by ibrokemypie** [aamirafridi/jQuery.Marquee#143]
Would it be possible to have a non-smooth or frame limited option, where the entire animation is shown using a chosen number of frames, giving a jumpy, pixel effect?
eg framelimit: 10; would make the whole animation of whatever width at whatever speed show in 10 frames, keeping the same time duration

**Comment by aamirafridi** [comment]
That would be nice to have. Not sure I will have time to implement this :P but PRs are welcomed :)
