### ISSUE TITLE
pauseOnCycle is not working

### ISSUE THREAD

**Issue by satindersinghsidhu** [aamirafridi/jQuery.Marquee#148]
I want to stop ticker for every 4 seconds after a cycle but **pauseOnCycle** is not working.

**Comment by satindersinghsidhu** [comment]
any update on this issue?

**Comment by aamirafridi** [comment]
Use setInterval and call toggle. Check examples for details

**Comment by naveed-fida** [comment]
As said above, `pauseOnCycle` isn't the appropriate option here. Closing.
