### ISSUE TITLE
Text Limit

### ISSUE THREAD

**Issue by pipechaves** [aamirafridi/jQuery.Marquee#149]
Him, first of all thanks for the plugin.

i was doing some tests of marquee vs this plugin and found that there is a text limit in this one. If more than 5828 characters are input then those after that count wont be shown.
I put 'right' as direction to see from where it start.

**Comment by aamirafridi** [comment]
Try increasing the width defined here https://github.com/aamirafridi/jQuery.Marquee/blob/master/jquery.marquee.js#L150
