### ISSUE TITLE
Toggle & Direction Up

### ISSUE THREAD

**Issue by paddyofurniture** [aamirafridi/jQuery.Marquee#152]
I am trying to get messages to scroll up into view, pause while fully visible in the div for a few seconds, then scroll up, out of view. 

The problem I am running into is getting it to toggle/pause when the message is fully in the div, and have the next time it scrolls up/back into the div to also be fully in the div. I am using setInterval & toggle, which I'm sure is the problem. I am hoping there's another way to do this. Any help would be appreciated.

[https://jsfiddle.net/paddy0furniture/h9oqLumc/11/](https://jsfiddle.net/paddy0furniture/h9oqLumc/11/)

**Comment by NateShoffner** [comment]
@paddyofurniture did you happen to solve this? Attempting a similar implementation but it's rather hacky and requires too much manual configuration.

**Comment by paddyofurniture** [comment]
@NateShoffner Not with jQuery.Marquee, I was able to achieve what I wanted with jquery.easy-ticker.
