### ISSUE TITLE
Jumpy Loop (Chrome)

### ISSUE THREAD

**Issue by amichel86** [aamirafridi/jQuery.Marquee#153]
Hello and thanks for your plugin! For some reason on Chrome only, when the transition has reached 1-2 loops, the text comes back "jumpy". Would you know what causes this?

Thanks in advance!

**Comment by rastislav-chynoransky** [comment]
The URL is not reachable, but I experienced jumpy loops because of the plugin being initialized too early before fonts were loaded, in such case load it after window load event:
```
$(window).on('load', function () {
  $('.marquee').marquee({
    // ...
  });
});

**Comment by peterkrupeya** [comment]
In my case it resolve problem with text jump

**Comment by amichel86** [comment]
@rastislav-chynoransky we ended up changing the effect but thanks so much!

**Comment by brandondeweese** [comment]
FYI...Still seeing this happen in Chrome only. Using $(window).on('load) does nothing.
