### ISSUE TITLE
Not working inside flexslider

### ISSUE THREAD

**Issue by antiantivirus** [aamirafridi/jQuery.Marquee#155]
Marquee not animating inside flexslider (http://flexslider.woothemes.com/). Marquee appears to load correctly but no animation is being applied to the elements.

this is the site i am working on http://sealive.flywheelsites.com/

code I am using for marquee
```
$('.hero-marquee').marquee({
    	duration: 1500,
    	duplicated: true,
    	pauseOnHover: true
    });
```

**Comment by antiantivirus** [comment]
this is what is appears in the style of the marquee element 

```
    width: 100000px;
    transform: translateX(0px);
    animation-play-state: running;
```

**Comment by aamirafridi** [comment]
I can see the animated marquee

**Comment by naveed-fida** [comment]
Tested it, and it works inside a felxslider slide, and there's no reason why it shouldn't. Closing.
