### ISSUE TITLE
Fire marquee on hover

### ISSUE THREAD

**Issue by pietrofxq** [aamirafridi/jQuery.Marquee#30]
There is some way to do the opposite of "pauseOnHover", leave the text stopped until you hover on it, and when you mouseout it comes back to normal? Just like spotify does in their app

**Comment by mcgrailm** [comment]
Another interesting point is that it starts off empty.

**Comment by nionios** [comment]
Hello, I know this is old, but for anyone stumbling upon this, I think implementing @aamirafridi 's code with the following change is best:
```
    $mq.hover(function () {
        $(this).marquee('resume');
    }, function () {
        $(this).marquee('pause');
    });
```

The only marquee triggered in this case is the one the user hovers and not every marquee on page.
