### ISSUE TITLE
Call from Web Service

### ISSUE THREAD

**Issue by Juanflu** [aamirafridi/jQuery.Marquee#32]
Hi Aamir:

I have an issue with my marquee. First of all I'll explain the context:
- I'm developing a ASP.NET web application, and when the page loads, I call **marquee.js**.
- This file contains a call to a Web Service that returns some data (This call is made with JSON)
- Then I set the _marquee_ body with **$(".marquee").html(responseData.d);**.
- After that I call the **$(".marquee").marquee** method.

The marquee is shown OK, but for a second the text is displayed like if no marquee was used and then it starts from the border of the div (like it should be).

I hope I'd explained clearly.

Thanks in advance.

**Comment by ravimallya** [comment]
@Juanflu , IMO, this is the expected behaviour of ajax requests. To avoid your issue, I suggest you either set a height for the .marquee class or else, you have to show some static content.
