### ISSUE TITLE
Not starting from outside the marquee

### ISSUE THREAD

**Issue by webchaz** [aamirafridi/jQuery.Marquee#33]
When scrolling from right to left, is there anyway so that the ticker won't start all the way right, but instead just start in the middle or left aligned, then continue scrolling to the left?

Thanks!

**Comment by onigetoc** [comment]
I'm looking for the same thing, 
My text is in the middle of a div and it's start only after a user action.
It's sould start at the middle where the text is before it start scrolling

**Comment by schwoortz** [comment]
A hack would be to change the two occurances of "margin-left" to "margin-right" in jquery.marquee.js
(found in the comments section of http://aamirafridi.com/jquery/jquery-marquee-plugin)

**Comment by nuke-ellington** [comment]
Check out the `startVisible` option.

**Comment by onigetoc** [comment]
I did my own Ticker with markee tags PLUS css
It mean it take 2 ways in one to be sure to work on almost every browser.
http://jsfiddle.net/onigetoc/cz2j99La/
