### ISSUE TITLE
how to detect the last text moved into marquee

### ISSUE THREAD

**Issue by smallg** [aamirafridi/jQuery.Marquee#37]
Now, the marquee plugin only trigger "finished" event when the last text move out marquee element.

but I want get other event is  the last text moved into marquee element, not moved out.

![qq 20141203174842](https://cloud.githubusercontent.com/assets/225962/5278505/19102cde-7b15-11e4-9373-cdf78342b26a.png)

when the message 5 moved into this marquee element, i want get some event and get other data to show into marquee.
how to detect this case?
thank you.

**Comment by aamirafridi** [comment]
Not possible with the plugin sorry.
