### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by blackfyre** [aamirafridi/jQuery.Marquee#38]
I believe that this repo could benefit from package management with bower, it really could speed up integration with existing projects!

**Comment by MWalid** [comment]
+1

**Comment by blackfyre** [comment]
Thanks, I'm aware of this, but real support for bower would be nice :smile:

**Comment by pincher2012** [comment]
It would be cool to add the installation instructions in the readme.md

**Comment by jaredcnance** [comment]
+1

**Comment by nuke-ellington** [comment]
```Bower.json``` and installation instructions are both part of the repo today.
