### ISSUE TITLE
Show Content By Default

### ISSUE THREAD

**Issue by HowdyMcGee** [aamirafridi/jQuery.Marquee#42]
When Marquee.js - is there a way to show the content by default then start the marquee? This is instead of showing nothing by default, then sliding in the content from whichever direction is it possible to instead how the content showing in it's default position, then start moving off-screen?

**Comment by mcgrailm** [comment]
It's weird to me that the content starts outside of the box and scrolls into it when the content is already there . It should scroll off then back on . At the very least the we should have the option to make it work that way .

**Comment by kcssm** [comment]
I am also looking for the same option. Has anyone found a way to achieve this?

**Comment by robotsushi** [comment]
You can comment out line 238 to fix this. It's an unsupported hack I made up. Good luck.

//$marqueeWrapper.css('margin-top', o.direction == 'up' ? containerHeight + 'px' : '-' + ((elHeight * 2) - o.gap) + 'px');

**Comment by HowdyMcGee** [comment]
I tried that robotsushi but it didn't seem to work.

I commented out this line: 

`$marqueeWrapper.css('margin-top', o.direction == 'up' ? containerHeight + 'px' : '-' + ((elHeight * 2) - o.gap) + 'px');`

Nothing unusually happened though.

**Comment by robotsushi** [comment]
When I wrote this I was using vertical scrolling starting from the bottom. If you are doing horizontal scrolling or scrolling down, im not sure if this would work. I would look for a line where o.direction === 'down' or whatever direction you are scrolling.

**Comment by HowdyMcGee** [comment]
This is a default, plain and simple marquee with the line you suggested commented out. I am using the latest version so I'm not sure if something has been updated in the meantime:

http://jsfiddle.net/eh2t6qhx/

**Comment by HowdyMcGee** [comment]
You're right, there's a vertical and horizontal, the horizontal is in the `else` statement: 

Working Fiddle: http://jsfiddle.net/eh2t6qhx/1/

Thanks robotsushi!

**Comment by nuke-ellington** [comment]
Check out the `startVisible` option.
