### ISSUE TITLE
Use translate(x,y) instead of animating Left/Top/Margin-Left/Margin-Top

### ISSUE THREAD

**Issue by Splendorr** [aamirafridi/jQuery.Marquee#43]
Hi! I love the plugin, and really appreciate you sharing it.

In my use, I've noticed the plugin is quite choppy in various environments. As I've been researching animation lately, I've learned that it's much better in almost instance to use the CSS animation "translate" to move elements vertically or horizontally, rather than changing the Left, Top, Margin-Left, or Margin-Top properties. These properties were never meant to be animated, and the calculations involved in changing them are more processor-intensive than the translate effect.

I've seen numerous reports about this. In my own anecdotal tests, when trying to mock up my own marquee animation in CSS, the translate effect is much smoother in every browser I have access to. I recognize it may not be available in all older browsers, but where it is, it's significantly smoother.

As far as I can tell, this plugin does not use "translate." I'm sure it would be a lot of work to change, but I thought I would mention this to you. In a page heavy with javascript and css animation effects, this marquee seems to have a visible impact on the overall performance of the site. I'll continue to search for my own optimizations, of course.

Thanks again, and best wishes!

**Comment by Splendorr** [comment]
Here's one great article as a citation about this.

http://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/

**Comment by mscreenie** [comment]
I came here just to post this, I've been using this plug-in for almost a year and have been learning new CSS3 methods. It seems translateX may be accelerated by the browser. 

This plugin uses margin, you could achieve the same result by using transalateX instead.

For now I'll be switching over to a pure CSS3 implementation, where frame 0% transalates from 100% to -100%.

**Comment by mscreenie** [comment]
I'd like to share my code:


	
.marquee-bottom {
    -webkit-animation: marquee 15s linear infinite;
}

        @-webkit-keyframes marquee {

            0% {
                -webkit-transform: translateX(100%);
            }
            100% {
                -webkit-transform: translateX(-100%); 
            }
        }

Thats it, if you need to animate left to right or vice versa you can use the reverse option. Change the speed by changing the duration. Add easing if you wish. And best of all it doesnt require a width which was important in my case.

**Comment by nuke-ellington** [comment]
Should have been closed automatically on merge.
