### ISSUE TITLE
Multiple elements in marquee? Marquee through a list?

### ISSUE THREAD

**Issue by ymdahi** [aamirafridi/jQuery.Marquee#46]
Let's say I have the following:

    <ul class="marquee">
      <li>My first message</li>
      <li>My second message</li>
    </ul>

Is it possible to marquee through each of my list elements? Currently, all elements are shown at the same time. It would be great if each list item was shown one after another.

**Comment by ymdahi** [comment]
Ah, never mind, you simply have to edit the css to display the items inline!

https://jsfiddle.net/ymdahi/sj2Lcq6x/

**Comment by alexiskattan** [comment]
thanks!
