### ISSUE TITLE
Glitchy in Safari 5.1+

### ISSUE THREAD

**Issue by zakpucci2** [aamirafridi/jQuery.Marquee#48]
I've tested this plugin, it is very light-weight and useful. Issue I have found is glitchy behavior in Safari.
Marquee will start, but while scrolling will be cut in half horizontally, top half will scroll, bottom half is static.

**Comment by aamirafridi** [comment]
You are right. Not sure why is it doing this? Will investigate when I get some time.

**Comment by tomgallagher** [comment]
+1 it's a great plugin, works well on everything except Safari, esp. on an Ipad. Just not smooth when moving across the page, a bit jerky.

**Comment by tomgallagher** [comment]
Is the iPad CSS3 support any good?

**Comment by aamirafridi** [comment]
I can clearly see that its jerky in safari even with css3 animations.
Try http://stackoverflow.com/questions/6481894/proper-way-to-optimize-css-3-animations-for-ios-mobile-safari
Other than this not sure I can help you on this :(
