### ISSUE TITLE
Marquee starts invisible

### ISSUE THREAD

**Issue by ar-** [aamirafridi/jQuery.Marquee#50]
I'm using a fairly slow Marquee. The problem is that it starts invisible. So you always have to wait a long time until you see the whole text. making it faster makes the text unreadable. Also if the user doesn't start reading the Marquee immediately, he will miss something if it runs too fast.

delayBeforeStart: 5000 is a good option. But the Marquee should be visible these 5 seconds and not invisible to make sense.

Maybe a new setting could be added, to set the start-position?

startVisible: true // default: false

**Comment by robotsushi** [comment]
You can comment out line 238 to fix this. It's an unsupported hack I made up. Good luck. 

//$marqueeWrapper.css('margin-top', o.direction == 'up' ? containerHeight + 'px' : '-' + ((elHeight * 2) - o.gap) + 'px');

**Comment by mrsarac** [comment]
Thanks for solution @robotsushi . It's worked.

**Comment by ar-** [comment]
Yes it worked for me too. Sorry, I forgot to report back.
