### ISSUE TITLE
left/right margin offset breaks Firefox animation

### ISSUE THREAD

**Issue by rossthedevigner** [aamirafridi/jQuery.Marquee#52]
This is probably known, but to have the text start at the very left of the marquee container one can use `margin-left: 20 !important' on`.js-marquee-wrapper`. Unfortunately this breaks all animations in Firefox.

**Comment by aamirafridi** [comment]
Sorry what do you mean by very left?

**Comment by wilsonwc** [comment]
This is an example of it not working in firefox http://beardyscaravan.com/

**Comment by aamirafridi** [comment]
Cannot see any marquee on the link so closing this
