### ISSUE TITLE
Plugin stops working when style tag in head is overritten

### ISSUE THREAD

**Issue by vetrov** [aamirafridi/jQuery.Marquee#55]
When style element exists in head section, marquee plugin relies on it. But sometimes this existing style element belongs to other third-party scripts and its content can be changed suddenly - in this case plugin stops working, because it saves there css3 keyframes.

Possible solutions:
* Always create new style element, don't rely on existing
* Add setting to force creating new style element when it's needed

**Comment by sauvainr** [comment]
+1 Have the same issue. 
I fixed it by injecting the CSS style into the '.js-marquee-wrapper' element instead of the head.
In line 330, replace
```
    $styles = $('style');

                    //Now add the keyframe animation to the head
                    if ($styles.length !== 0) {
                        //Bug fixed for jQuery 1.3.x - Instead of using .last(), use following
                        $styles.filter(":last").append(keyframeCss);
                    } else {
                        $('head').append('<style>' + keyframeCss + '</style>');
                    }
```
By
```
$marqueeWrapper.append('<style>' + keyframeCss + '</style>');
```

**Comment by aamirafridi** [comment]
Humm good point. Will have a look

**Comment by aamirafridi** [comment]
@sauvainr do you mind creating a pull request with the fix?

**Comment by aamirafridi** [comment]
https://github.com/aamirafridi/jQuery.Marquee/commit/56270e38dde783d7f3b5321cbacf62b6acc562a0
