### ISSUE TITLE
Does not work in Edge browser

### ISSUE THREAD

**Issue by xumix** [aamirafridi/jQuery.Marquee#56]
subj, no errors, just no animation

**Comment by yuval-a** [comment]
Works here. Version 20.10240

**Comment by xumix** [comment]
http://en.investmoscow.ru/
![2015-09-07 14 49 52 moscow investment portal - main page - microsoft edge](https://cloud.githubusercontent.com/assets/250118/9716146/c0671832-556f-11e5-95f7-cd7663b2f1a9.png)

**Comment by nicedawg** [comment]
FWIW, it wasn't working for me in IE11, (or IE11 in IE10 mode), but then I set allowCss3Support: false in the marquee options, and it started working.

**Comment by xumix** [comment]
it works OK if I add the style width: 100% to he div

**Comment by xumix** [comment]
$this.width() gives 0 so duration is NaN here 
```o.duration = ((parseInt(elWidth, 10) + parseInt(containerWidth, 10)) / parseInt(containerWidth, 10)) * o.duration;```

**Comment by aamirafridi** [comment]
@xumix is this resolved?

**Comment by daslicht** [comment]
so how to fix please ?

**Comment by xumix** [comment]
@aamirafridi nope, this is not resolved

**Comment by xumix** [comment]
@daslicht set container div width

**Comment by daslicht** [comment]
My rendered Marquee HTML looks like this at the moment : 
```
<div id="marquee_container" style="overflow-x:hidden">
    <div id="marquee_text">
         <div style="width: 100000px; margin-left: 0px; animation: marqueeAnimation-9585491 39.9652s linear 0s infinite;" class="js-marquee-wrapper">
             <div class="js-marquee" style="margin-right: 20px; float: left;">Marquee Text</div>
             <div class="js-marquee" style="margin-right: 20px; float: left;">Marquee Tex</div>
             <style>@-webkit-keyframes marqueeAnimation-9585491  { 100%  {margin-left:-1146px}}</style>       
         </div>
   </div>
</div>
```

I tried setting the width to 100% of _marquee_container_ and _marquee_text_, but that did not have any effect in Edge ?

**Comment by daslicht** [comment]
anyone please?

**Comment by aamirafridi** [comment]
Did you tried this https://github.com/aamirafridi/jQuery.Marquee/issues/56#issuecomment-170545812

**Comment by daslicht** [comment]
this ?
```
$this.width() gives 0 so duration is NaN here 
o.duration = ((parseInt(elWidth, 10) + parseInt(containerWidth, 10)) / parseInt(containerWidth, 10)) * o.duration;
```

**Comment by aamirafridi** [comment]
ops. sorry this https://github.com/aamirafridi/jQuery.Marquee/issues/56#issuecomment-145985563

**Comment by daslicht** [comment]
Disabling css support will result is a very un-smooth marquee in all other browsers...

**Comment by daslicht** [comment]
Ok I tried it again with the css setting and it works on Edge, lets see if its smooth enough for my client :)

**Comment by rohan-sethi** [comment]
Hi ! I'm new to GitHub. For the IE issue I tried out :
` $('.marquee').toggle().toggle();`
Works fine now!! Can anyone verify ?

**Comment by elevenkey** [comment]
@rohan-sethi it's good for me. Edge 25.10586.0.0

**Comment by watermark** [comment]
Perhaps the same issue as #70

**Comment by aamirafridi** [comment]
Should work now https://github.com/aamirafridi/jQuery.Marquee/commit/fda1f2e0d54e8d930a053bfb7fb82c2a34e066be
