### ISSUE TITLE
Ability to configure scroll 'speed' rather than 'duration' for flexible width containers

### ISSUE THREAD

**Issue by brendon** [aamirafridi/jQuery.Marquee#58]
I've noticed that the `duration` setting doesn't seem to take into account the width of the container so the scroll speed with be slower with narrower containers.

Is there a way to specify a standard speed (perhaps converted into a duration via a calculation based on the width of the container)?

**Comment by brendon** [comment]
I found that (leaving your code intact) making the duration a factor of the container width seems to fix the problem:

```
duration: 10 * $('.marquee').width()
```

**Comment by brendon** [comment]
Of course it malfunctions for marquees that are shorter than their containing element.

**Comment by aamirafridi** [comment]
You are right. I just confirmed. I assumed that you will have 1 marquee on the page and you just adjust its duration.

**Comment by aamirafridi** [comment]
@brendon can you create PR for the fix?

**Comment by brendon** [comment]
Lol, I'll try to send my mind back 5 months :D I'll give it a go :)
