### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by QRMarketing** [aamirafridi/jQuery.Marquee#59]
I can't seem to get it to load. I get this: "Uncaught TypeError: undefined is not a function" error. Read a lot of Stack Flow articles on JQuery conflicts and nothing seems to work. Perhaps something else on the page conflicts with it.

Any idea on how to get this to run stand alone?

HTML (it loads the plug in ok):
<div class="marquee" pauseOnHover="true">
                <span id="text_stuff"></span>
            </div>

$(document).ready(function() {
    $('.marquee').marquee();
}

**Comment by aamirafridi** [comment]
This is not a bug with the plugin. Please goto http://aamirafridi.com/jquery/jquery-marquee-plugin and add comment there with a link to your project so I can have a look.
