### ISSUE TITLE
Bug on AJAX example @codepen

### ISSUE THREAD

**Issue by hippostar** [aamirafridi/jQuery.Marquee#62]
Your code re-binds the "finished" event every time (exponentially) so you end up having the showRandomMarquee function called a billion times and the browser tab crashes.

See this one for fixed version : http://codepen.io/anon/pen/jWbbLe

**Comment by lixiansky** [comment]
I have the same problem

**Comment by aamirafridi** [comment]
Thanks. I have updated the pen http://codepen.io/aamirafridi/pen/ayBmF :)
