### ISSUE TITLE
start in the end of line

### ISSUE THREAD

**Issue by t0n1zz** [aamirafridi/jQuery.Marquee#63]
so if my text move from left to right can i make it when page load the first text already at right side of the line? i just want to make that when my page load the newsticker already fill the area, not just starting to move but already moving with entire newsticker area filled with text / duplicate text

hope you understand what i mean

**Comment by nuke-ellington** [comment]
If it is sufficient for you that the text starts aligned to the left of the container, you could check out my pull request labeled "startVisible".

**Comment by AndrzejSala** [comment]
Or my pull request. I too have problem, that i would like have element filled container.

**Comment by aamirafridi** [comment]
The pull request is tested and merged
