### ISSUE TITLE
Image scrolling issue.

### ISSUE THREAD

**Issue by ahgan84** [aamirafridi/jQuery.Marquee#69]
I plan to put image into your marquee js. Like what u mentioned in your readme, you need to put the below so that it can calculate the image width accurately:
`$(window).load(function() {
    $('.marquee').marquee();
});`

This function will load the marquee after the webpage load out. 

But what if I only load the marquee after I received a command. For example:

`receivedCom = function(){
          $('.marquee').marquee({duration: 8000});      
      });`

I cannot put $(window).load into the receivedCom function. It won't run. Any idea how?

**Comment by aamirafridi** [comment]
I am confused about what you are asking but you can try this.

```
var marqueeImagesLoaded = false;
$(window).load(function() { marqueeImagesLoaded = true });
receivedCom = function(){  if(marqueeImagesLoaded) $('.marquee').marquee({duration: 8000}); });
```
