### ISSUE TITLE
Latest version does not work in edge 25.x

### ISSUE THREAD

**Issue by asimism** [aamirafridi/jQuery.Marquee#70]
The latest version does not work in edge 25.x. However version 1.3.3 is well supported on all browsers.

**Comment by watermark** [comment]
Ran into the same issue.  Edge doesn't like the fact that the "<style>" tag isn't in the "<head>".  I fixed it by changing "$marqueeWrapper.append('<style>' + keyframeCss + '</style>');" to "$('head').append('<style>' + keyframeCss + '</style>');"

**Comment by aamirafridi** [comment]
this should be fixed. PR merged
