### ISSUE TITLE
Sync between multiple marquees with different lengths

### ISSUE THREAD

**Issue by dani-z** [aamirafridi/jQuery.Marquee#76]
Hi,

I have multiple marquees on the same page with different text lengths. First iteration works just fine, when the second iteration fires, all the messages are off because each marquee is independent. Is there a way of syncing them? Say shortest one to wait for the longest one to finish and then to fire again?

Many thanks,

**Comment by aamirafridi** [comment]
Not sure what exactly do you want but you cannot sync 2 marquees. Although you can try `finished` event for each marquee.
