### ISSUE TITLE
How to use inside a table?

### ISSUE THREAD

**Issue by z3ntu** [aamirafridi/jQuery.Marquee#77]
Is it possible to use this plugin inside a table?
I have a problem which is [demonstrated in this codepen](http://codepen.io/z3ntu/pen/pbVVZo).

**Comment by rohan-sethi** [comment]
Hi, it worked when I gave some width to the `div` inside `td`.

**Comment by aamirafridi** [comment]
it should http://jsfiddle.net/aamir/jc7F3/1515/
