### ISSUE TITLE
startVisible breaks duplicated option

### ISSUE THREAD

**Issue by ama-gi** [aamirafridi/jQuery.Marquee#79]
If the startVisible option is set to true and the duplicated option is true, content gets duplicated too late.

**Comment by nuke-ellington** [comment]
Hello @ama-gi,

Have you tried messing around with the `gap` option?

**Comment by aamirafridi** [comment]
Seems to be working fine. Please reopen with example if needed. http://jsfiddle.net/aamir/jc7F3/1514/

**Comment by n0xx** [comment]
Same problem here.
It looks like it's duplicating elements too late so when all items scroll whole thing, script making a gap about 1/4 of container width before append duplicated elements.
Gap does not seems to fix anything in this issue.

In my case i put href's with logotypes inside container.
