### ISSUE TITLE
jquery v3.1.1

### ISSUE THREAD

**Issue by flythird** [aamirafridi/jQuery.Marquee#82]
Hello ! from frog land ! in the south

First, thank you to share your work.

It worked fine until i upgrade my application with jquery v3.1.1.

Now, i have an exception when i call the method $('#myid').marquee('destroy')
"
r.find(...).andSelf is not a function 
Object.destroy
"
So.. maybe i did a mistake. I call the destroy method without knowing if my object has already an instance. 
since jquery v3.1.1 exception. 

have you see this behavior before.
stop..i searched and found: 
  ".andSelf"  is deprecated and replaced by " .addBack()" 

also this issue is not an issue now maybe a new version ....

thank you for your attention

alien, from the smelling cheeses country (always in the south of france)

**Comment by aamirafridi** [comment]
Thanks for this. Can you please create a pull request with the fix after testing it? :)

**Comment by flythird** [comment]
frog land again ! 

Sorry my english is not fluent.
i don't use git and i don't want to make a mistake by trying to forward the solution.
i use your library  every days and the correction works.

So jquery v3.1.1 need this above correction and sorry hope you will correct it for netx version

**Comment by nuke-ellington** [comment]
This is already fixed by now.
