### ISSUE TITLE
Destroy not working 

### ISSUE THREAD

**Issue by ToujouAya** [aamirafridi/jQuery.Marquee#84]
The method destroy is not working at version 1.4.0
I tried this code to change marquee with ajax content follow this (http://codepen.io/aamirafridi/pen/ayBmF) but it's not working on version 1.4.0.
This only work at version 1.3.0

**Comment by nuke-ellington** [comment]
Closing this since I haven't heard of any related issues with the current v1.5.0. I the problem persists please comment and we will look into this.
