### ISSUE TITLE
Please add a LICENCE file

### ISSUE THREAD

**Issue by Spudley** [aamirafridi/jQuery.Marquee#85]
Hi

I see from your package.json file that you are using the ISC license for this code. Could you please add a LICENSE file to the repo to confirm this? Thank you.

**Comment by aamirafridi** [comment]
Will do. thanks

**Comment by julmot** [comment]
+1

**Comment by koreus7** [comment]
+1

**Comment by Leo-Mahon** [comment]
+1

**Comment by aamirafridi** [comment]
done
