### ISSUE TITLE
"andSelf" method (not working in jQuery 3) still present in minified version of js.

### ISSUE THREAD

**Issue by johnunclesam** [aamirafridi/jQuery.Marquee#91]
"andSelf" method (not working in jQuery 3) still present in minified version of js.

Why?

**Comment by Nanyx** [comment]
Got the same error, change the "andSelf()" by "addBack()" as in the non-minimify version.
It does the work for me

**Comment by mkarajohn** [comment]
Bumping this. 

```
Uncaught TypeError: b.find(...).andSelf is not a function
    at Object.destroy (jquery.marquee.min.js:6)
    at HTMLDivElement.<anonymous> (jquery.marquee.min.js:6)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.f.fn.marquee (jquery.marquee.min.js:5)
```

**Comment by ryanlin1986** [comment]
Incompatible with jquery 3, any chance to support it ?

**Comment by johnunclesam** [comment]
`andSelf()` is replaced in jQuery3 with `addBack()`.

The minified master version of jQuery.Marquee is still with `andSelf()`.

Can you try and PR please, @Nanyx, @mkarajohn, @ryanlin1986? I can't PR right now().

**Comment by mkarajohn** [comment]
@johnunclesam I don't think this repo is actively maintained anymore. I have made a [fork](https://github.com/mkarajohn/jQuery.Marquee) of it where I correct the minified file.

However since the original minified file still has the obsolete method, and the unminified doesn't, that tells me that the minified file is probably a few iterations back from the unminified. So I may actually change the `main` entry in the `package.json`, in my fork, to point to the unminified code, since webpack will take care of minifying it for me anyway.

**Comment by johnunclesam** [comment]
@mkarajohn correct about the minify version.

Can we open an issue for the new fork? Maybe someone and the author @aamirafridi can help. Maybe he can switch this repo to you. Can you @aamirafridi?

**Comment by nuke-ellington** [comment]
@johnunclesam, @mkarajohn, @ryanlin1986 - Thank you guys for pointing this out. I updated the minified file.
If you have any pull requests in the future hit me up, and I will try to process them. Aamir seems busy, but he's active from time to time.

**Comment by mkarajohn** [comment]
All's well then, a fork is not needed. Thanks for letting us know this is not a dead repo.

**Comment by aamirafridi** [comment]
I am very busy these days with projects and that is correct that this project is not actively maintained. Instead of fork, why not create a pull request and I will happy to review and merge.

**Comment by johnunclesam** [comment]
Yes @aamirafridi, thanks for your precious time. We'll PR.

**Comment by aamirafridi** [comment]
@johnunclesam 😂  "precious time". no problem 😝
@mkarajohn, @johnunclesam I have added you guys as collaborator. Please help in maintaining the project.
