### ISSUE TITLE
URGENT: From 1.3.2 methods don't work anymore 

### ISSUE THREAD

**Issue by johnunclesam** [aamirafridi/jQuery.Marquee#92]
~~If you change in this pen (http://codepen.io/aamirafridi/pen/ayBmF) jQuery from 2 to 3 it does'nt work anymore.~~

~~Why?~~

~~I'm using these files in codepen's dependencies:~~

~~https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js~~
~~https://cdn.rawgit.com/aamirafridi/jQuery.Marquee/master/jquery.marquee.js~~

I thought it was a jQuery3 problem, but then I realized that these lines have created the problem. How can we solve that?

https://github.com/aamirafridi/jQuery.Marquee/blob/1.3.2/jquery.marquee.js#L80-L83

In 1.3.1:
```javascript
//Just unwrap the elements that has been added using this plugin
$this.css('visibility', 'hidden').html($this.find('.js-marquee:first'));
//This is to prevent the sudden blink
setTimeout(function () {
  $this.css('visibility', 'visible');
}, 0);
```

In 1.3.2
```javascript
//Unbind all events
$this.find("*").andSelf().unbind();
//Just unwrap the elements that has been added using this plugin
$this.html($this.find('.js-marquee:first').html());
```

If I remove this line:

```javascript
$this.find("*").andSelf().unbind();
```

it works.

**Comment by johnunclesam** [comment]
This is the new pen with new dependencies: http://codepen.io/anon/pen/rjBaVY

**Comment by aamirafridi** [comment]
Looks like you solved the issue. I will be happy to review a PR if needed.

**Comment by johnunclesam** [comment]
Can you PR yourself please? I don't know how to do.
