### ISSUE TITLE
Container size question

### ISSUE THREAD

**Issue by paulmadore** [aamirafridi/jQuery.Marquee#97]
I'm trying to use this on a huge piece of text at the top of the screen. I finally figured out that the height element is required for it to run, but there seems to be a lot of space in between them. I would prefer if the text is present when the page loads. Suggestions?

**Comment by arifhussain353** [comment]
@paulmadore  i did with setting `margin-top:0 !important` to `.js-marquee-wrapper` class with css.I hope this will work for you.

**Comment by nuke-ellington** [comment]
As far as having the text visible on page load, that can be achieved via the "startVisible" option.
https://github.com/aamirafridi/jQuery.Marquee#methods

Hope that helps.

**Comment by aamirafridi** [comment]
startVisible, probably with duplicated option
