### ISSUE TITLE
Slow down existing marquee

### ISSUE THREAD

**Issue by matronator** [aamirafridi/jQuery.Marquee#99]
Hi, first off, great plugin! I just wanted to know if there is a way to slow down already existing marquee. Let's say I have a marquee with duration set to 1200 and I would like to change the duration to 2400 when I hover over the marquee element, so it would create nice effect of slowing down when hovering over. I tried doing it several different ways, but none of them does what I want.

First I tried simply this (inside the hover function):
`$mr.marquee({duration: 1200});`
That seems to have deleted my old marquee and creating new one with just the duration parameter, restarting the marquee from the beginning.

Then I tried setting the duration based on another variable:
```
var dur = 1;
marquee({duration: 1200 * dur});
```
On hover:
`dur = 2;`
This doesn't work because the marquee sets its parameters only once and that's during declaration (creation).

Lastly I tried destroying the old marquee and creating a new one with different duration, but that resets the marquee making it start again instead of continuing from the position it got destroyed on.

Any idea how I might achieve what I'm looking for?

**Comment by aamirafridi** [comment]
There is no way to do this at the moment. In your example whenever you do .marquee, you are actually applying the plugin again.
